traffic-lights:
  - name: "/salvador/barbalho/rua1/1"
    cycle_time: 90
    state: "GREEN"
    columns: 3
    lines: 2
    intensity: "HIGH" 

  - name: "/salvador/barbalho/rua1/2"
    cycle_time: 90
    state: "GREEN"
    columns: 4
    lines: 3
    intensity: "MEDIUM"

  - name: "/salvador/barbalho/rua1/3"
    cycle_time: 90
    state: "GREEN"
    columns: 3
    lines: 3
    intensity: "LOW"

  - name: "/salvador/barbalho/rua2/1"
    cycle_time: 90
    state: "GREEN"
    columns: 2
    lines: 4
    intensity: "MEDIUM"

  - name: "/salvador/barbalho/rua3/1"
    cycle_time: 90
    state: "GREEN"
    columns: 2
    lines: 4
    intensity: "MEDIUM"

intersections:
  - name: "rua1xrua2xrua3"
    traffic-lights: ["/salvador/barbalho/rua1/1", "/salvador/barbalho/rua2/1", "/salvador/barbalho/rua3/1"]