traffic-lights:
  - name: "/salvador/barbalho/rua1/1"
    cycle_time: 60
    state: "GREEN"
    columns: 3
    lines: 2
    intensity: "HIGH" 
  - name: "/salvador/barbalho/rua1/2"
    cycle_time: 30
    state: "GREEN"
    columns: 3
    lines: 2
    intensity: "MEDIUM" 
  - name: "/salvador/barbalho/rua1/3"
    cycle_time: 60
    state: "RED"
    columns: 3
    lines: 2
    intensity: "LOW" 

  - name: "/salvador/barbalho/rua2/1"
    cycle_time: 60
    state: "GREEN"
    columns: 2
    lines: 4
    intensity: "MEDIUM"

intersections:
  - name: "rua1xrua2"
    traffic-lights: ["/salvador/barbalho/rua1/2", "/salvador/barbalho/rua2/1"]
  
green_waves:
  - name: "rua1"
    traffic_lights:
      - "/salvador/barbalho/rua1/1"
      - "/salvador/barbalho/rua1/2"
      - "/salvador/barbalho/rua1/3"
    travel_time_ms: 1000