traffic-lights:
  - name: "/salvador/rua-rodoviarios/sentido-cabula/1"
    cycle_time: 60
    state: "GREEN"
    columns: 3
    lines: 2
    intensity: "HIGH" 
  - name: "/salvador/rua-rodoviarios/sentido-cabula/2"
    cycle_time: 30
    state: "GREEN"
    columns: 3
    lines: 2
    intensity: "MEDIUM" 
  - name: "/salvador/rua-silveira-martins/sentido-cabula/1"
    cycle_time: 60
    state: "RED"
    columns: 3
    lines: 2
    intensity: "LOW" 

  - name: "/salvador/rua-silveira-martins/sentido-rotula-abacaxi/1"
    cycle_time: 60
    state: "RED"
    columns: 3
    lines: 2
    intensity: "LOW" 

  - name: "/salvador/rua-thomaz-gonzaga/sentido-rotula-abacaxi/1"
    cycle_time: 60
    state: "GREEN"
    columns: 2
    lines: 4
    intensity: "MEDIUM"

intersections:
  - name: "praca-f-manoel"
    traffic-lights: ["/salvador/rua-rodoviarios/sentido-cabula/2", "/salvador/rua-thomaz-gonzaga/sentido-rotula-abacaxi/1"]
  
green_waves:
  - name: "sentido-cabula-1"
    traffic_lights:
      - "/salvador/rua-rodoviarios/sentido-cabula/1"
      - "/salvador/rua-rodoviarios/sentido-cabula/2"
      - "/salvador/rua-silveira-martins/sentido-cabula/1"
    travel_time_ms: 2000

sync_groups:
  - name: "travessia-pedestres-sentido-cabula-1"
    traffic_lights:
      - "/salvador/rua-silveira-martins/sentido-cabula/1"
      - "/salvador/rua-silveira-martins/sentido-rotula-abacaxi/1" 