traffic-lights:
  - name: "/salvador/barbalho/rua1/1"
    cycle_time: 20
    state: "GREEN"
    columns: 3
    lines: 2
    intensity: "HIGH" 

  - name: "/salvador/barbalho/rua2/1"
    cycle_time: 20
    state: "GREEN"
    columns: 2
    lines: 4
    intensity: "MEDIUM"

  - name: "/salvador/barbalho/rua3/1"
    cycle_time: 20
    state: "GREEN"
    columns: 2
    lines: 4
    intensity: "MEDIUM"

intersections:
  - name: "rua1xrua2"
    traffic-lights: ["/salvador/barbalho/rua1/1", "/salvador/barbalho/rua2/1"]
  
green_waves:
  - name: "Onda Verde Rua 1"
    traffic_lights:
      - "/salvador/barbalho/rua1/1"
      - "/salvador/barbalho/rua1/2"
      - "/salvador/barbalho/rua1/3"
    travel_time_ms: 8000